[project]
root = 
window_title = 

[graphics] # Runtime graphics settings
default_resolution_width = 1920
default_resolution_height = 1080
fullscreen = true
vsync = true
target_fps = 60

[audio] # Audio mixer settings (OpenAL)
backend = openal
fallback = true
master_volume = 0.8
sample_rate = 44100
buffer_size = 2048

[audio.windows]
device = # Default Windows device
frequency = 48000
channels = stereo
hrtf = true

[audio.linux]
device = # OpenAL chooses best backend (PulseAudio / PipeWire / ALSA)
frequency = 48000
channels = stereo
hrtf = true

[audio.r36s]
# Try hardware first, then your engine falls back
frequency = 44100
channels = stereo
hrtf = false
device = hw:CARD=rockchiprk817co,DEV=0
device_fbk = dmix:CARD=rockchiprk817co,DEV=0

[memory] # Memory pool sizes
texture_pool_mb = 64
audio_pool_mb = 32
script_pool_mb = 8

[logging] # Debug output
log_to_screen = true
log_to_console = true
log_to_file = true
log_file = game.log
